import yaml from 'js-yaml'

export function downloadJson(data: unknown, filename: string) {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })
  downloadBlob(blob, filename)
}

export function downloadYaml(data: unknown, filename: string) {
  const blob = new Blob([yaml.dump(data, { sortKeys: false })], { type: 'application/x-yaml' })
  downloadBlob(blob, filename)
}

// 将规则数据转换为 CSV 格式
export function downloadCsv(data: { rules: Record<string, unknown>[] }, filename: string) {
  if (!data.rules || data.rules.length === 0) {
    downloadBlob(new Blob(['No rules available'], { type: 'text/csv' }), filename)
    return
  }

  // 获取所有可能的列
  const columns = new Set<string>()
  data.rules.forEach((rule) => {
    Object.keys(rule).forEach((key) => columns.add(key))
  })
  
  const columnArray = Array.from(columns)
  
  // 构建 CSV 内容
  const rows: string[] = []
  
  // 表头
  rows.push(columnArray.join(','))
  
  // 数据行
  data.rules.forEach((rule) => {
    const values = columnArray.map((col) => {
      const value = rule[col]
      if (value === undefined || value === null) return ''
      const str = typeof value === 'object' ? JSON.stringify(value) : String(value)
      // 处理包含逗号或引号的值
      if (str.includes(',') || str.includes('"') || str.includes('\n')) {
        return `"${str.replace(/"/g, '""')}"`
      }
      return str
    })
    rows.push(values.join(','))
  })
  
  const csvContent = '\uFEFF' + rows.join('\n') // BOM for Excel
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8' })
  downloadBlob(blob, filename)
}

// 转换为 XML 格式
export function downloadXml(data: { rules: Record<string, unknown>[] }, filename: string) {
  const rules = data.rules || []
  let xml = '<?xml version="1.0" encoding="UTF-8"?>\n<rules>\n'
  
  rules.forEach((rule) => {
    xml += '  <rule>\n'
    Object.entries(rule).forEach(([key, value]) => {
      const safeKey = key.replace(/[^a-zA-Z0-9_]/g, '_')
      if (typeof value === 'object' && value !== null) {
        xml += `    <${safeKey}>${escapeXml(JSON.stringify(value))}</${safeKey}>\n`
      } else {
        xml += `    <${safeKey}>${escapeXml(String(value))}</${safeKey}>\n`
      }
    })
    xml += '  </rule>\n'
  })
  
  xml += '</rules>'
  const blob = new Blob([xml], { type: 'application/xml' })
  downloadBlob(blob, filename)
}

// 转换为 Logstash 配置文件格式
export function downloadLogstashConfig(data: { rules: Record<string, unknown>[] }, filename: string) {
  const rules = data.rules || []
  let config = '# Logstash Configuration Generated by RIZHI\n'
  config += 'filter {\n'
  
  rules.forEach((rule) => {
    const operator = rule.operator as string
    config += `  # ${operator}\n`
    
    switch (operator) {
      case 'grok':
        config += `  grok {\n`
        config += `    match => { "${rule.source_field || 'message'}" => "${rule.pattern}" }\n`
        config += `  }\n`
        break
      case 'json':
        config += `  json {\n`
        config += `    source => "${rule.source_field || 'message'}"\n`
        config += `  }\n`
        break
      case 'regex':
        config += `  grok {\n`
        config += `    match => { "${rule.source_field || 'message'}" => "${rule.pattern}" }\n`
        config += `  }\n`
        break
      case 'kv_split':
        config += `  kv {\n`
        config += `    source => "${rule.source_field}"\n`
        config += `    field_split => "${rule.pair_separator || '&'}"\n`
        config += `    value_split => "${rule.kv_separator || '='}"\n`
        config += `  }\n`
        break
      case 'csv':
        config += `  csv {\n`
        config += `    source => "${rule.source_field || 'message'}"\n`
        config += `    separator => "${rule.delimiter || ','}"\n`
        config += `    columns => [${(rule.fields as string || '').split(',').map((f) => `"${f.trim()}"`).join(', ')}]\n`
        config += `  }\n`
        break
      case 'mutate':
      case 'remove':
        config += `  mutate {\n`
        if (rule.fields) {
          const fields = (rule.fields as string).split(',').map((f) => `"${f.trim()}"`)
          config += `    remove_field => [${fields.join(', ')}]\n`
        }
        config += `  }\n`
        break
      case 'timestamp':
        config += `  date {\n`
        config += `    match => ["${rule.source_field}", "${rule.format}"]\n`
        if (rule.timezone) {
          config += `    timezone => "${rule.timezone}"\n`
        }
        config += `  }\n`
        break
      default:
        config += `  # TODO: Implement ${operator} manually\n`
        config += `  # Parameters: ${JSON.stringify(rule)}\n`
    }
  })
  
  config += '}\n'
  const blob = new Blob([config], { type: 'text/plain' })
  downloadBlob(blob, filename)
}

// 复制到剪贴板
export async function copyToClipboard(data: unknown): Promise<boolean> {
  try {
    const text = typeof data === 'string' ? data : JSON.stringify(data, null, 2)
    await navigator.clipboard.writeText(text)
    return true
  } catch {
    // 降级方案
    const textArea = document.createElement('textarea')
    textArea.value = typeof data === 'string' ? data : JSON.stringify(data, null, 2)
    textArea.style.position = 'fixed'
    textArea.style.left = '-9999px'
    document.body.appendChild(textArea)
    textArea.focus()
    textArea.select()
    try {
      document.execCommand('copy')
      return true
    } catch {
      return false
    } finally {
      document.body.removeChild(textArea)
    }
  }
}

// 导出为 Fluentd 配置
export function downloadFluentdConfig(data: { rules: Record<string, unknown>[] }, filename: string) {
  const rules = data.rules || []
  let config = '# Fluentd Configuration Generated by RIZHI\n\n'
  config += '<filter **>\n'
  config += '  @type record_transformer\n'
  config += '  <record>\n'
  
  rules.forEach((rule) => {
    config += `    # ${JSON.stringify(rule)}\n`
  })
  
  config += '  </record>\n'
  config += '</filter>\n'
  
  const blob = new Blob([config], { type: 'text/plain' })
  downloadBlob(blob, filename)
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}
